INSERT INTO locations(id, district) VALUES (1,'Waru, Sidoarjo');
INSERT INTO locations(id, district) VALUES (2,'Wonorejo, Surabaya');
INSERT INTO locations(id, district) VALUES (3,'Kenjeran, Surabaya');
INSERT INTO locations(id, district) VALUES (4,'Buduran, Sidoarjo');
INSERT INTO locations(id, district) VALUES (5,'Balongbendo, Sidoarjo');
INSERT INTO locations(id, district) VALUES (6,'Gresik Kota, Gresik');
INSERT INTO locations(id, district) VALUES (7,'Pakal, Surabaya');
INSERT INTO locations(id, district) VALUES (8,'Pondok Tjandra, Sidoarjo');
INSERT INTO locations(id, district) VALUES (9,'Sidoarjo, Sidoarjo');
INSERT INTO locations(id, district) VALUES (10,'Gubeng, Surabaya');
INSERT INTO locations(id, district) VALUES (11,'Tulangan, Sidoarjo');
INSERT INTO locations(id, district) VALUES (12,'Dharma Husada, Surabaya');
INSERT INTO locations(id, district) VALUES (13,'Taman, Sidoarjo');
INSERT INTO locations(id, district) VALUES (14,'Citraland, Surabaya');
INSERT INTO locations(id, district) VALUES (15,'Sedati, Sidoarjo');
INSERT INTO locations(id, district) VALUES (16,'Mulyosari, Surabaya');
INSERT INTO locations(id, district) VALUES (17,'Gresik, Gresik');
INSERT INTO locations(id, district) VALUES (18,'Sukolilo, Surabaya');
INSERT INTO locations(id, district) VALUES (19,'Driyorejo, Gresik');
INSERT INTO locations(id, district) VALUES (20,'Rungkut, Surabaya');
INSERT INTO locations(id, district) VALUES (21,'Jenggolo, Sidoarjo');
INSERT INTO locations(id, district) VALUES (22,'Darmo Permai, Surabaya');
INSERT INTO locations(id, district) VALUES (23,'Kebomas, Gresik');
INSERT INTO locations(id, district) VALUES (24,'Sukodono, Sidoarjo');
INSERT INTO locations(id, district) VALUES (25,'Wiyung, Surabaya');
INSERT INTO locations(id, district) VALUES (26,'Porong, Sidoarjo');
INSERT INTO locations(id, district) VALUES (27,'Lakarsantri, Surabaya');
INSERT INTO locations(id, district) VALUES (28,'Benjeng, Gresik');
INSERT INTO locations(id, district) VALUES (29,'Benowo, Surabaya');
INSERT INTO locations(id, district) VALUES (30,'Mulyorejo, Surabaya');
INSERT INTO locations(id, district) VALUES (31,'Tegalsari, Surabaya');
INSERT INTO locations(id, district) VALUES (32,'Larangan, Sidoarjo');
INSERT INTO locations(id, district) VALUES (33,'Candi, Sidoarjo');
INSERT INTO locations(id, district) VALUES (34,'Menganti, Gresik');
INSERT INTO locations(id, district) VALUES (35,'Kebonsari, Surabaya');
INSERT INTO locations(id, district) VALUES (36,'Gedangan, Sidoarjo');
INSERT INTO locations(id, district) VALUES (37,'Gununganyar, Surabaya');
INSERT INTO locations(id, district) VALUES (38,'Medokan Ayu, Surabaya');
INSERT INTO locations(id, district) VALUES (39,'Bungah, Gresik');
INSERT INTO locations(id, district) VALUES (40,'Diponegoro, Surabaya');
INSERT INTO locations(id, district) VALUES (41,'Graha, Surabaya');
INSERT INTO locations(id, district) VALUES (42,'Sidayu, Gresik');
INSERT INTO locations(id, district) VALUES (43,'Surabaya Kota, Surabaya');
INSERT INTO locations(id, district) VALUES (44,'Karangpilang, Surabaya');
INSERT INTO locations(id, district) VALUES (45,'Manukan, Surabaya');
INSERT INTO locations(id, district) VALUES (46,'Manyar, Gresik');
INSERT INTO locations(id, district) VALUES (47,'Manyar, Surabaya');
INSERT INTO locations(id, district) VALUES (48,'Tambaksari, Surabaya');
INSERT INTO locations(id, district) VALUES (49,'Sawahan, Surabaya');
INSERT INTO locations(id, district) VALUES (50,'Sambikerep, Surabaya');
INSERT INTO locations(id, district) VALUES (51,'Sukomanunggal, Surabaya');
INSERT INTO locations(id, district) VALUES (52,'Unimas Garden Waru , Sidoarjo');
INSERT INTO locations(id, district) VALUES (53,'Wonocolo, Surabaya');
INSERT INTO locations(id, district) VALUES (54,'Tenggilis Mejoyo, Surabaya');
INSERT INTO locations(id, district) VALUES (55,'Jemursari, Surabaya');
INSERT INTO locations(id, district) VALUES (56,'Balongpanggang, Gresik');
INSERT INTO locations(id, district) VALUES (57,'Kedamean, Gresik');
INSERT INTO locations(id, district) VALUES (58,'Wadungasri, Sidoarjo');
INSERT INTO locations(id, district) VALUES (59,'Bubutan, Surabaya');
INSERT INTO locations(id, district) VALUES (60,'Tunjungan, Surabaya');
INSERT INTO locations(id, district) VALUES (61,'Krian, Sidoarjo');
INSERT INTO locations(id, district) VALUES (62,'Wringinanom, Gresik');
INSERT INTO locations(id, district) VALUES (63,'Gayungan, Surabaya');
INSERT INTO locations(id, district) VALUES (64,'Tandes, Surabaya');
INSERT INTO locations(id, district) VALUES (65,'Pabean Cantikan, Surabaya');
INSERT INTO locations(id, district) VALUES (66,'Perak, Surabaya');
INSERT INTO locations(id, district) VALUES (67,'Kendangsari, Surabaya');
INSERT INTO locations(id, district) VALUES (68,'Petemon, Surabaya');
INSERT INTO locations(id, district) VALUES (69,'Duduk Sampeyan, Gresik');
INSERT INTO locations(id, district) VALUES (70,'Tanggulangin, Sidoarjo');
INSERT INTO locations(id, district) VALUES (71,'Krembangan, Surabaya');
INSERT INTO locations(id, district) VALUES (72,'Wonoayu, Sidoarjo');
INSERT INTO locations(id, district) VALUES (73,'Wisata Bukit Mas, Surabaya');
INSERT INTO locations(id, district) VALUES (74,'Lidah Kulon, Surabaya');
INSERT INTO locations(id, district) VALUES (75,'Krembung, Sidoarjo');
INSERT INTO locations(id, district) VALUES (76,'Pakuwon Indah, Surabaya');
INSERT INTO locations(id, district) VALUES (77,'Kutisari, Surabaya');
INSERT INTO locations(id, district) VALUES (78,'Sidoarjo, Surabaya');
INSERT INTO locations(id, district) VALUES (79,'Kertajaya, Surabaya');
INSERT INTO locations(id, district) VALUES (80,'Babatan, Surabaya');
INSERT INTO locations(id, district) VALUES (81,'Ketintang, Surabaya');
INSERT INTO locations(id, district) VALUES (82,'Nginden, Surabaya');
INSERT INTO locations(id, district) VALUES (83,'Jambangan, Surabaya');
INSERT INTO locations(id, district) VALUES (84,'Kedung Baruk, Surabaya');
INSERT INTO locations(id, district) VALUES (85,'Bulak, Surabaya');
INSERT INTO locations(id, district) VALUES (86,'Kebraon, Surabaya');
INSERT INTO locations(id, district) VALUES (87,'Rungkut Industri, Surabaya');
INSERT INTO locations(id, district) VALUES (88,'Waru, Surabaya');
INSERT INTO locations(id, district) VALUES (89,'Sidokerto, Sidoarjo');
INSERT INTO locations(id, district) VALUES (90,'Semolowaru, Surabaya');
INSERT INTO locations(id, district) VALUES (91,'Kalisari, Surabaya');
INSERT INTO locations(id, district) VALUES (92,'Simomulyo, Surabaya');
INSERT INTO locations(id, district) VALUES (93,'Genteng, Surabaya');
INSERT INTO locations(id, district) VALUES (94,'Dukuh Pakis, Surabaya');
INSERT INTO locations(id, district) VALUES (95,'Pakuwon City, Surabaya');
INSERT INTO locations(id, district) VALUES (96,'Kapasan, Surabaya');
INSERT INTO locations(id, district) VALUES (97,'Dukuh Kupang, Surabaya');
INSERT INTO locations(id, district) VALUES (98,'Keputih, Surabaya');
INSERT INTO locations(id, district) VALUES (99,'Simokerto, Surabaya');
INSERT INTO locations(id, district) VALUES (100,'Lidah Wetan, Surabaya');
INSERT INTO locations(id, district) VALUES (101,'Wonokromo, Surabaya');
INSERT INTO locations(id, district) VALUES (102,'Sutorejo, Surabaya');
INSERT INTO locations(id, district) VALUES (103,'Mojoarum, Surabaya');
INSERT INTO locations(id, district) VALUES (104,'Menganti, Surabaya');
INSERT INTO locations(id, district) VALUES (105,'Raya A Yani, Surabaya');
INSERT INTO locations(id, district) VALUES (106,'Raya Darmo, Surabaya');
INSERT INTO locations(id, district) VALUES (107,'Tembok Dukuh, Surabaya');
INSERT INTO locations(id, district) VALUES (108,'Middle East Ring Road, Surabaya');
INSERT INTO locations(id, district) VALUES (109,'Margorejo, Surabaya');
INSERT INTO locations(id, district) VALUES (110,'Pakis, Surabaya');
INSERT INTO locations(id, district) VALUES (111,'Dr Sutomo, Surabaya');
INSERT INTO locations(id, district) VALUES (112,'Ngagel, Surabaya');
INSERT INTO locations(id, district) VALUES (113,'Kureksari, Surabaya');
INSERT INTO locations(id, district) VALUES (114,'Jagir, Surabaya');
INSERT INTO locations(id, district) VALUES (115,'Semampir, Surabaya');
INSERT INTO locations(id, district) VALUES (116,'Kembang Jepun, Surabaya');
INSERT INTO locations(id, district) VALUES (117,'Panjang Jiwo, Surabaya');
INSERT INTO locations(id, district) VALUES (118,'Undaan, Surabaya');
INSERT INTO locations(id, district) VALUES (119,'Pakuwon, Surabaya');
INSERT INTO locations(id, district) VALUES (120,'Kupang, Surabaya');
INSERT INTO locations(id, district) VALUES (121,'Mayjen Sungkono, Surabaya');
INSERT INTO locations(id, district) VALUES (122,'Cerme, Gresik');
INSERT INTO locations(id, district) VALUES (123,'Banyu Urip, Surabaya');
INSERT INTO locations(id, district) VALUES (124,'Tarik, Sidoarjo');
INSERT INTO locations(id, district) VALUES (125,'Asemrowo, Surabaya');
INSERT INTO locations(id, district) VALUES (126,'Alun-Alun Contong, Surabaya');
INSERT INTO locations(id, district) VALUES (127,'Galaxy, Surabaya');
INSERT INTO locations(id, district) VALUES (128,'Laguna, Surabaya');
INSERT INTO locations(id, district) VALUES (129,'Paneleh, Surabaya');
INSERT INTO locations(id, district) VALUES (130,'Balong Sari, Surabaya');
INSERT INTO locations(id, district) VALUES (131,'Hr Muhammad, Surabaya');
INSERT INTO locations(id, district) VALUES (132,'Kedung Doro, Surabaya');
INSERT INTO locations(id, district) VALUES (133,'Prambon, Sidoarjo');
INSERT INTO locations(id, district) VALUES (134,'Margomulyo, Surabaya');
INSERT INTO locations(id, district) VALUES (135,'Karang Poh, Surabaya');
INSERT INTO locations(id, district) VALUES (136,'Buntaran, Surabaya');
INSERT INTO locations(id, district) VALUES (137,'Gadel, Surabaya');
INSERT INTO locations(id, district) VALUES (138,'Keputran, Surabaya');
INSERT INTO locations(id, district) VALUES (139,'Jabon, Sidoarjo');
INSERT INTO locations(id, district) VALUES (140,'Ambengan, Surabaya');
INSERT INTO locations(id, district) VALUES (141,'Gundih, Surabaya');
INSERT INTO locations(id, district) VALUES (142,'Bendungan Bening, Sidoarjo');
