services:
  app-api:
    depends_on:
      - app-db
    image: house-price-api
    build: .
    container_name: house-api
    restart: unless-stopped
    ports:
      - "8000:80"
    env_file:
      - .env
    networks:
      - house-network

  app-db:
    image: postgres:17-bookworm
    container_name: house-data
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rumah123
    volumes:
      - house-data:/var/lib/postgresql/data
    networks:
      - house-network

volumes:
  house-data:

networks:
  house-network: